name: Bug Report (FiveM)
description: File a bug report for FiveM related issues
title: "🐞 "
labels: ["fivem", "bug", "triage"]
assignees:
  - 
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out this bug report!
        Only bug related issues are accepted, so please refrain yourself from submitting any other requests, especially support requests.
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Please be clear and concise
      placeholder: 
    validations:
      required: true
  - type: input
    id: expectation
    attributes:
      label: Expected result
      description: What were you expecting to happen instead?
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Reproduction steps
      description: |
        This is important to us. Fill in the exact steps you took, test and remove any steps that aren't relevant.
        Also make sure these steps result in the same result(s) this bug report is actually about.
        Issue reports that fail to deliver these steps may be closed without any feedback.
      placeholder: |
        1. 
        2. 
        3. 
        4. 
      render: bash
    validations:
      required: true
  - type: dropdown
    id: game-version
    attributes:
      label: Game version
      description: Which version(s) of GTA 5 is this issue related to?
      multiple: true
      options:
        - 2699
        - 2545
        - 2372
        - 2189
        - 2060
        - 1604
    validations:
      required: true
  - type: dropdown
    id: update-channel
    attributes:
      label: Update channel
      description: Can be found by going into FiveM settings.
      options:
        - Release
        - Beta
        - Latest (Unstable, Canary)
        - Built from source
    validations:
      required: true
  - type: input
    id: versions-extra
    attributes:
      label: Specific version
      description: Please fill in the specific version(s) if this issue is related to any specific build.
      placeholder: FiveM v1.0.0.5817, Server v1.0.0.5817
